export enum CredentialsActionType {
  START_LOADING_CREDENTIALS = "CREDENTIALS:START_LOADING_CREDENTIALS",
  LOAD_CREDENTIALS = "CREDENTIALS:LOAD_CREDENTIALS",
  ADD_NEW_CREDENTIALS = "CREDENTIALS:ADD_NEW_CREDENTIALS",
  UPDATE_CREDENTIALS = "CREDENTIALS:UPDATE_CREDENTIALS",
  DELETE_CREDENTIALS = "CREDENTIALS:DELETE_CREDENTIALS",
  UPDATE_ENCRYPTOR = "CREDENTIALS:UPDATE_ENCRYPTOR",
  CLEAR_STATE = "CREDENTIALS:CLEAR_STATE",
}
