export enum VaultActionType {
  START_LOADING_VAULT = "VAULT:START_LOADING_VAULT",
  LOAD_VAULT = "VAULT:LOAD_VAULT",
  LOAD_ITEMS_IN_BATCH = "VAULT:LOAD_VAULT_ITEMS_IN_BATCH",
  ADD_NEW_VAULT_ITEM = "VAULT:ADD_NEW_VAULT_ITEM",
  UPDATE_VAULT_ITEM = "VAULT:UPDATE_VAULT_ITEM",
  DELETE_VAULT_ITEM = "VAULT:DELETE_VAULT_ITEM",
  CLEAR_STATE = "VAULT:CLEAR_STATE",
}
