name: Deploy to Firebase Hosting

on:
  push:
    branches: [master]

jobs:
  firebase_hosting_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTHSENTRY }}'
          channelId: live
          projectId: ${{ github.env.FIREBASE_PROJECT_ID }}  